### ISSUE TITLE
NCSU OSGeoREL group

### ISSUE THREAD

**Issue by baharmon** [tangible-landscape/tangible-landscape.github.io#1]
**Name:** NCSU Open Source Geospatial Research and Education Laboratory
**Institution:** North Carolina State University
**Department:** Center for Geospatial Analytics
**Team:** Anna Petrasova, Vaclav Petras, Helena Mitasova, and Brendan Harmon
**Website:** [http://tangible-landscape.github.io/](http://tangible-landscape.github.io/)
**Latitude and longitude:** 35.7818, -78.6764

Geojson

```
{ "type": "Feature",
  "geometry": {
      "type": "Point",
      "coordinates": [-78.6764, 35.7818]
  },
  "properties": {
      "name": "NCSU Open Source Geospatial Research and Education Laboratory",
      "institution": "North Carolina State University",
      "department": "Center for Geospatial Analytics",
      "team": "Anna Petrasova, Vaclav Petras, Helena Mitasova, and Brendan Harmon",
      "website": "http:\/\/tangible-landscape.github.io\/",
      "marker-color": "#111",
      "marker-symbol": "marker"
    }
},
```

**Comment by gubuntu** [comment]
- Group name: St Johns College Geography Department with Kartoza
- Institution: St Johns College
- Department: Geography
- Team members: Bridget Fleming, Sam Jones, Matthew Jones, Peter Henning, Gavin Fleming
- Website: http://stjohnscollege.co.za/ http://kartoza.com 
- Date: 8 Oct 2016
- Latitude and longitude: -26.1775, 28.0566

**Comment by baharmon** [comment]
Added.

**Comment by jietaowang** [comment]
Name: Wuhan Tangible GIS Lab
Institution: Wuhan Center of China Geological Survey
Department: Hydrogeology and Environmental Geology
Team: Wang Jietao
Latitude and longitude: 30.458577, 114.421366

**Comment by petrasovaa** [comment]
Thank you! Added you the the community wiki:
https://github.com/tangible-landscape/grass-tangible-landscape/wiki/Community#wuhan-tangible-gis-lab

and to the map:

http://tangible-landscape.github.io/

**Comment by wenzeslaus** [comment]
I have tried to clarify at the [Community page](https://github.com/tangible-landscape/grass-tangible-landscape/wiki/Community) that new issues should be opened for new places, but I'm leaving this unlocked as a fallback.
