### ISSUE TITLE
New Group

### ISSUE THREAD

**Issue by blisabli** [tangible-landscape/tangible-landscape.github.io#3]
Group name: Geoinformatics Research Group
Institution: University Of Brawijaya, Malang, East Java, Indonesia
Department: Faculty of Computer Science
Team members: Cendi Tito Rahman, Adhi Isti Febriandhika, Fatwa Ramdani, M.Chandra Saputra
Website : http://gis.filkom.ub.ac.id/
Date: 10/16/2017
Latitude and longitude : -7.953736, 112.614839

**Comment by baharmon** [comment]
I have added your group to the map. 
I will also add you to the [community page](https://github.com/tangible-landscape/grass-tangible-landscape/wiki/Community) as well.
Do you have any pictures of the project to share with us?

**Comment by blisabli** [comment]
sorry for my late to send you a picture, here a picture 
![sistem](https://user-images.githubusercontent.com/32833128/31926298-e73c16a8-b8b7-11e7-9711-860bf0111ec5.jpg)

**Comment by blisabli** [comment]
Yes i Have a picture. Sorry for replying your email now. here the
pircture[image:
Gambar sisip 1]

2017-10-23 22:23 GMT+07:00 Brendan Harmon <notifications@github.com>:
