### ISSUE TITLE
new location: PSWMRU

### ISSUE THREAD

**Issue by SarahGoslee-USDA** [tangible-landscape/tangible-landscape.github.io#4]
Name: USDA-ARS Pasture Systems and Watershed Management Research Unit
Team: Sarah Goslee and Jeff Gonet
Institution: US Department of Agriculture
Department: Agricultural Research Service
Website: https://www.ars.usda.gov/northeast-area/up-pa/pswmru/
Latitude and longitude: -77.8619, 40.8033

Geojson

{ "type": "Feature",
  "geometry": {
      "type": "Point",
      "coordinates": [-77.8619, 40.8033]
  },
  "properties": {
      "name": "USDA-ARS Pasture Systems and Watershed Management Research Unit",
      "institution": "US Department of Agriculture",
      "department": "Agricultural Research Service",
      "team": "Sarah Goslee and Jeff Gonet",
      "website": "https:\/\/www.ars.usda.gov\/northeast-area\/up-pa\/pswmru\/",
      "marker-color": "#111",
      "marker-symbol": "marker"
    }
},

**Comment by baharmon** [comment]
Added. If you take any photos that you would like share, please add them to your entry on the [community wiki](https://github.com/tangible-landscape/grass-tangible-landscape/wiki/Community#usda-ars-pasture-systems-and-watershed-management-research-unit).
