### ISSUE TITLE
[pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!

### ISSUE THREAD

**Issue by jietaowang** [tangible-landscape/tangible-landscape.github.io#5]
Dear all friends!

I connected my kinect with my computer(Linuxmint 19.2) . When I click the 'start' button, in the 'tangible Landscape', it does not work. and show this message. Does anyone know the reason? 

I am tring to set up the first Tangible GIS lab in Wuhan, China.  Please help me to fix it.  Thanks!

![kdtree](https://user-images.githubusercontent.com/3294029/72233871-c3be0200-3604-11ea-866e-4c16b42c126f.jpg)

**Comment by wenzeslaus** [comment]
Closing this as this was resolved through other channels.

General occurrence of this error is now addressed at:

https://github.com/tangible-landscape/grass-tangible-landscape/wiki/Troubleshooting

Wuhan is now on the map and on the community page:

http://tangible-landscape.github.io/
https://github.com/tangible-landscape/grass-tangible-landscape/wiki/Community

And a designated place to ask questions - grass-tangible-landscape repo issues - is now mentioned at the wiki:

https://github.com/tangible-landscape/grass-tangible-landscape/wiki
